package com.dbs.portal.ui.component.view;

public enum FormFieldType {
	
	LABEL, PASSWORDFIELD, TEXTFIELD, MASKED_TEXTFIELD, NUMERICFIELD, TEXTAREA, COMBOBOX, CHECK_BOX, RADIO_BUTTON, CHECK_BOX_GROUP, RADIO_BUTTON_GROUP, DATETIME, LIST_SELECT, UPLOAD, TWINS_COL, BUTTON;
	
}
